POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "rootfuddle",
    "firstname": "Simon Johnsonx",
    "lastname": "Big daddyy",
    "location": "Lagoss",
    "phone": 12345678,
    "email": "samueljackson@gmail.com",
    "password": "saladandme"
}